main:
  push:
    - docker:
        image: node:lts
        volumes:
          - /root/.npm:cow
      stages:
        - name: Install dependencies
          script: |
            npm i
        - name: build 
          script: |
            npm run docs:build
            cd .vitepress/dist
        - name: commit
          image: tencentcom/git-commit:latest
          commands: |
            cd .vitepress/dist
            git init
            git config --global user.name "CI Bot"
            git config --global user.email "ci-bot@aingdesk.com"
            git remote add origin https://cnb.cool/aingdesk/website.git
            git checkout -b build
            git add .
            git commit -m "Auto deploy to build branch"
            git push -f origin build
$:
  vscode:
    - services:
        - docker
      docker:
        build: 
          dockerfile: .ide/Dockerfile
      stages:
        - name: Install dependencies
          script: |
            npm i