main:
  push:
    - docker:
        image: node:lts
        volumes:
          - /root/.npm:cow
      stages:
        - name: Install dependencies
          script: |
            npm i
        - name: build 
          script: npm run docs:build
        - name: resolve
          type: cnb:resolve
          options:
            key: build
    - stages:
        - name: await the build
          type: cnb:await
          options:
            key: build
        - name: set token
          image: tencentcom/git-set-credential:latest
          settings:
            userName: aingdesk
            userEmail: support@aingdesk.com
            loginUserName: ${CNB_TOKEN_USERNAME}
            loginPassword: ${CNB_TOKEN}

        - name: commit
          image: tencentcom/git-commit:latest
          commands: |
            cd .vitepress/dist
            git add .
            git commit -m "Auto deploy to build branch"
            git push origin build
$:
  vscode:
    - services:
        - docker
      docker:
        build: 
          dockerfile: .ide/Dockerfile
      stages:
        - name: Install dependencies
          script: |
            npm i