main:
  push:
    - docker:
        image: node:lts
        volumes:
          - /root/.npm:cow
      stages:
        - name: Install dependencies
          script: |
            npm i
        - name: build 
          script: |
            npm run docs:build
            cd .vitepress/dist
        - name: commit
          image: tencentcom/git-commit:latest
          commands: |
            cd .vitepress/dist
            git config --global user.name "CI Bot"
            git config --global user.email "ci-bot@aingdesk.com"
            git checkout -B build  # 切换到 build 分支（如果不存在则创建）
            git add .  # 添加 dist 目录中的所有文件
            git commit -m "Auto deploy to build branch" || echo "No changes to commit"
            git push -f origin build  # 强制推送到 build 分支
$:
  vscode:
    - services:
        - docker
      docker:
        build: 
          dockerfile: .ide/Dockerfile
      stages:
        - name: Install dependencies
          script: |
            npm i