main:
  push:
    - docker:
        image: node:lts
        volumes:
          - /root/.npm:cow
      stages:
        - name: Install dependencies
          script: |
            npm i
        - name: build 
          script: npm run docs:build
        - name: resolve
          type: cnb:resolve
          options:
            key: build
    - stages:
        - name: await the build
          type: cnb:await
          options:
            key: build
        - name: commit
          image: tencentcom/git-commit:latest
          commands: |
            ls -a
            cd .vitepress
            ls -a
            cd .vitepress/dist
            git add .
            git commit -m "Auto deploy to build branch"
            git push origin build
$:
  vscode:
    - services:
        - docker
      docker:
        build: 
          dockerfile: .ide/Dockerfile
      stages:
        - name: Install dependencies
          script: |
            npm i